# Generated by Django 5.0.4 on 2024-04-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.adtitle'),
        ),
    ]
