# Generated by Django 5.0.4 on 2024-04-16 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описання'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to='ads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(max_length=200, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='ads.adtitle'),
        ),
        migrations.AlterField(
            model_name='adtitle',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації'),
        ),
    ]
