# Generated by Django 5.0.4 on 2024-04-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_description_alter_ad_image_alter_ad_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtitle',
            name='pub_date',
        ),
    ]
